In [ ]:
NIKUNJ DEEP UPADHYAY
ENTC B1
25070123081
exp 9
study of numpy library

In [4]:
#DECLARATION OF NUMPY
import numpy as np

a=np.array([1,10,20,30,40,50,500])
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(b)

[  1  10  20  30  40  50 500]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
#DIMENSION OF ARRAY
print(a.ndim)
print(b.ndim)

1
2


In [6]:
#SIZE OF ARRAY
print(a.size)
print(b.size)

7
9


In [7]:
#SHAPE OF ARRAY
print(a.shape)
print(b.shape)

(7,)
(3, 3)


In [17]:
#TYPE OF ARRAY
print(a.dtype)
print(b.dtype)

int64
int64


In [18]:
# IN-BUILT FUNCTIONS USING NUMPY
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [20]:
np.eye((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [23]:
np.arange(1,12,2)

array([ 1,  3,  5,  7,  9, 11])

In [24]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [25]:
np.linspace(0,1,4)

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [26]:
print(b*2)
print(a+5)
#print(c)
#print(d)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[  6  15  25  35  45  55 505]


In [27]:
np.mean(a)

np.float64(93.0)

In [28]:
np.median(a)

np.float64(30.0)

In [29]:
np.max(a)

np.int64(500)

In [30]:
np.min(a)

np.int64(1)

In [31]:
np.sum(a)

np.int64(651)